# Generated by Django 5.2.9 on 2026-01-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0002_rename_tittle_property_title_city_city_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_img',
            field=models.ImageField(default=1, upload_to='property_photo'),
            preserve_default=False,
        ),
    ]
