# Generated by Django 5.2.9 on 2026-01-21 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0003_property_property_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='property_img',
            new_name='img',
        ),
    ]
