# Generated by Django 5.2.9 on 2026-01-21 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0004_rename_property_img_property_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='img',
        ),
    ]
